- name: Configure SVIs and IP addresses
  hosts: Dis1
  gather_facts: no
  become: yes  # Add this line to enable privilege escalation
  vars_files:
    - pass.yml
    - VLAN_vars.yml

  tasks:
    - name: Configure SVI for VLANs
      ios_config:
        lines:
          - "interface Vlan{{ item.vlan_id }}"
          - "description {{ item.department }}"
          - "ip address 192.168.{{ item.vlan_id }}.2 {{ item.subnet_mask }}"
          - "ip helper-address 10.10.10.5"
          - "no shut"
      loop: "{{ vlans }}"
      when: inventory_hostname == "Dis1"

    - name: Configure trunk interfaces
      ios_config:
        lines:
          - "interface {{ item }}"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
      loop: "{{ dis_Trunking_interfaces }}"
      loop_control:
        loop_var: item

    - name: Save configuration
      ios_command:
        commands:
          - "write"
