---
- name: Configure SVIs and IP addresses
  hosts: Dis2
  gather_facts: no
  vars_files:
    - pass.yml
    - VLAN_vars.yml

  tasks:
    - name: Include VLAN variables
      include_vars:
        file: VLAN_vars.yml
        name: vlans

    - name: Configure SVIs and IP addresses
      include_vars:
        file: VLAN_vars.yml
        name: vlans

    - name: Configure SVI for {{ item.department }}
      ios_config:
        lines:
          - "interface Vlan{{ item.vlan_id }}"
          - "description {{ item.department }}"
          - "ip address 192.168.{{ item.vlan_id }}.3 255.255.255.0"
      when: inventory_hostname == "Dis2" and item.vlan_id is defined and item.vlan_id|int >= 10 and item.vlan_id|int <= 19
      with_items: "{{ vlans }}"
      loop_control:
        loop_var: item

    - name: Configure trunk interfaces
      ios_config:
        lines:
          - "interface {{ item }}"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
      with_items: "{{ dis_Trunking_interfaces }}"
      loop_control:
        loop_var: item

    - name: Save configuration
      ios_command:
        commands:
          - "write"
