---
- name: Configure SVIs and IP addresses
  hosts: Dis1
  gather_facts: no
  vars_files:
    - pass.yml
    - VLAN_vars.yml

  tasks:
    - name: Configure SVI for VLANs 10 to 14
      ios_config:
        lines:
          - interface Vlan {{ item.vlan_id }}
          - description {{ item.department }}
          - ip address 192.168.{{ item.vlan_id }}.2 {{ item.subnetmask }}
          - ip helper-address 10.10.10.5
          - no shut
      with_items: "{{ vlans }}"
      when: item.vlan_id >= 10 and item.vlan_id <= 14

    - name: Configure SVI for VLANs 15 to 19
      ios_config:
        lines:
          - interface Vlan {{ item.vlan_id }}
          - description {{ item.department }}
          - ip address 192.168.{{ item.vlan_id }}.3 {{ item.subnetmask }}
          - ip helper-address 10.10.10.5
          - no shut
      with_items: "{{ vlans }}"
      when: item.vlan_id >= 15 and item.vlan_id <= 19

    - name: Configure trunk interfaces
      ios_config:
        lines:
          - interface {{ item }}
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - switchport trunk native vlan 1
      with_items: "{{ dis_Trunking_interfaces }}"

    - name: Save configuration
      ios_command:
        commands:
          - write
