---
- name: Configure SVIs, IP addresses, and trunk interfaces
  hosts: F2_HO 
  gather_facts: no
  vars_files:
    - pass.yml
    - VLAN_vars.yml

  tasks:
    
    - name: Configure trunk interfaces
      ios_config:
        lines:
          - "interface {{ item }}"
          - "switchport trunk encapsulation dot1q"
          - "switchport mode trunk"
      with_items: "{{ F2_Trunking_interfaces }}"
      loop_control:
        loop_var: item
    - name: Configure access interfaces
      ios_config:
        lines:
         - int e0/2
         - switchport mode access
         - switchport access vlan 11
         - int e0/3
         - switchport mode access
         - switchport access vlan 12
         - int e1/0
         - switchport mode access
         - switchport access vlan 13
    - name: Save configuration
      ios_command:
        commands:
          - write