---
- name: Configure Trunking interfaces
  hosts: Access 
  gather_facts: no
  vars_files:
    - pass.yml
    - VLAN_vars.yml

  tasks:
    - name: Configure trunk interfaces on All Switch Access
      ios_config:
        lines:
          - interface {{ item }}
          - switchport trunk encapsulation dot1q
          - switchport mode trunk
          - switchport trunk native vlan 99
      with_items: "{{ access_Trunking_interfaces }}"

    - name: Save configuration
      ios_command:
        commands:
          - write