---
- name: Configure SpanningTree on Dis1 
  hosts: Core1_MB
  gather_facts: no
  vars_files:
    - pass.yml
    - VLAN_vars.yml
  tasks:

    - name: Configure STP for VLANs 20-21 (Root)
      ios_config:
        lines:
          - spanning-tree mode rapid-pvst
          - spanning-tree vlan {{ item.vlan_id }} root primary
      with_items: "{{ vlans }}"
      when: item.vlan_id == 20 and item.vlan_id == 21

    - name: Configure STP for VLANs 22-23 (Second)
      ios_config:
        lines:
          - spanning-tree mode rapid-pvst
          - spanning-tree vlan {{ item.vlan_id }} root Secondary
      with_items: "{{ vlans }}"
      when: item.vlan_id == 22 and item.vlan_id == 23

    - name: Save configuration
      ios_command:
        commands:
          - write
